# Sử dụng image chứa Node.js và npm
FROM node:16

# Đặt thư mục làm việc trong container
WORKDIR /app

# Sao chép package.json và package-lock.json vào thư mục làm việc
COPY package*.json ./

# Tắt cảnh báo từ npm install
RUN npm install --no-warnings

# Sao chép các tệp dự án vào thư mục làm việc
COPY . .

# Tắt kiểm tra lỗ hổng bảo mật và cài đặt gói
RUN npm install --legacy-peer-deps

# Tạo biến môi trường để bỏ qua kiểm tra ESLint
ENV SKIP_PREFLIGHT_CHECK=true

# Build ứng dụng React
RUN npm run build

# Cài đặt serve để chạy ứng dụng đã build
RUN npm install -g serve

# Chạy ứng dụng khi container được khởi chạy
CMD ["serve", "-s", "build"]
